name: Release
on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: "Build workflow run ID (optional - will use latest successful run if not provided)"
        required: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Get version from CMake
        id: cmake_version
        uses: DarwinInnovation/cmake-project-version-action@v1.0

      - name: Download Windows artifact
        uses: dawidd6/action-download-artifact@v20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          workflow_conclusion: success
          name: QontrolPanel_win64_msvc2022
          run_id: ${{ inputs.workflow_run_id }}
          if_no_artifact_found: fail

      - name: Download Windows Installer
        uses: dawidd6/action-download-artifact@v20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          workflow_conclusion: success
          name: QontrolPanel_Installer
          run_id: ${{ inputs.workflow_run_id }}
          if_no_artifact_found: fail

      - name: Create release and tag
        run: |
          VERSION="${{ steps.cmake_version.outputs.version }}"
          echo "Creating release for version: $VERSION"

          git tag $VERSION
          git push origin $VERSION

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2.6.1
        with:
          tag_name: ${{ steps.cmake_version.outputs.version }}
          name: ${{ steps.cmake_version.outputs.version }}
          body: ""
          draft: true
          fail_on_unmatched_files: true
          files: |
            QontrolPanel_win64_msvc2022.zip
            QontrolPanel_Installer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
